language: python
python:
    - 2.7.8
    - 2.7
    - pypy
    - 3.3
    - 3.4
    - 3.5
    - 3.6

_base_envs:
- &pypy_base
  python: pypy
  env:
  - PYPY_VERSION=pypy2-5.7.1
  - PYENV_ROOT="$HOME/.pyenv"
  - PATH="$PYENV_ROOT/bin:$PATH"
  dist: trusty
  sudo: required
  addons:
    apt:
      packages:
      - make
      - build-essential
      - libssl-dev
      - zlib1g-dev
      - libbz2-dev
      - libreadline-dev
      - libsqlite3-dev
      - wget
      - curl
      - llvm
      - libncurses5-dev
      - libncursesw5-dev
      - xz-utils
      - tk-dev
  before_install:
  - |
    if [ -f "$PYENV_ROOT/bin/pyenv" ]
    then
      eval "$(pyenv init -)"
      eval "$(pyenv virtualenv-init -)"
      pyenv update
    else
      rm -rf "$PYENV_ROOT"
      curl -L https://raw.githubusercontent.com/pyenv/pyenv-installer/master/bin/pyenv-installer | bash
      eval "$(pyenv init -)"
      eval "$(pyenv virtualenv-init -)"
    fi
    pyenv install --skip-existing --keep --verbose "$PYPY_VERSION"
    pyenv shell "$PYPY_VERSION"

matrix:
  fast_finish: true
  include:
  - python: 3.6
    env: TOXENV=pre-commit
  - <<: *pypy_base
    python: pypy3
    env:
    - PYPY_VERSION=pypy3.5-5.7.1-beta
    - PYENV_ROOT="$HOME/.pyenv"
    - PATH="$PYENV_ROOT/bin:$PATH"

install:
  - pip install -r requirements.txt
  - pip install coveralls

services:
  - mongodb

before_script:
  - sudo redis-server /etc/redis/redis.conf --requirepass 'secret'
  - sleep 3
  - python -m fomalhaut.tests.load_config
  - sleep 3
  - python -m fomalhaut.runserver &
  - sleep 3
  - python -m fomalhaut.tests.api_server &
  - sleep 3

script:
#  - python -m unittest discover -s fomalhaut -p "*_test.py"
  - coverage run --source=fomalhaut -m unittest discover -s fomalhaut -p "*_test.py"

after_success:
  coveralls
